### ISSUE TITLE
New name for Kassy and organisation migration

### ISSUE THREAD

**Issue by mrkno** [concierge/Concierge#100]
The name `Kassy` no longer really represents what this project is about so we should get a new one. 
We also need to migrate to an organization so that we can split pre-installed modules into their own repositories.

**Comment by ParasDPain** [comment]
Since the main feature of the project is providing a modular and integrable I/O channel, how does `manobot` (Manual-Bot) sound for the name? Otherwise how about `Mot` (Modular Bot) ?

**Comment by mrkno** [comment]
Other suggestions so far proposed by others:
- concierge
- neo
- lycanthropic
- varlet
- villein
- scullion
- murcia
- somnus
- mutunus tutunus
- aeternitas

**Comment by ParasDPain** [comment]
Well I just watched the movie so how about `Chappie

**Comment by mrkno** [comment]
@ParasDPain you seem to have taken a reasonably active interest in this project, when this migration finally takes place would you like to be added as a member of the organization?

**Comment by ParasDPain** [comment]
@mrkno Thanks :) I'd really appreciate that.

**Comment by mrkno** [comment]
I've created the `concierge` organization. This name seemed like the most memorable and easy to understand proposed, it also sort of describes what Kassy now does.

We will migrate to the organization after the current work backlog is complete.

**Comment by Awarua-** [comment]
Hint hint to me :ok_hand:

**Comment by Awarua-** [comment]
Migration to new name happened a few days ago. still have to move existing modules to their own kpm modules.
