### ISSUE TITLE
IRC gateway

### ISSUE THREAD

**Issue by lagleki** [concierge/Concierge#121]
Although Slack integration partially solves this a direct integration to IRC would be more beneficial for some people.

**Comment by mrkno** [comment]
I would agree. We will probably do this in the future or get it by default through Hubot compatibility.

**Comment by lagleki** [comment]
I can't make hubot-irc work with Kassy. Any help?

**Comment by mrkno** [comment]
What is the specific error?

**Comment by p0358** [comment]
There is always possibility to rewrite hubot-irc to Concierge integration format.

**Comment by fallaciousreasoning** [comment]
I've made a (very) basic integration for IRC here [here](https://github.com/concierge/irc), which we can extend as we go.
