### ISSUE TITLE
Error running !help in Skype

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Concierge#133]
Receiving this error on the `!help` command in Skype:

```Something went wrong!Failed to send message.```

Seems like maybe the message text is too long because `!help ping` works as expected. 

It seems that it did work in Skype at least once, as I can see the output in my Skype chat history, but am getting this error consistently now.

**Comment by mrkno** [comment]
Can you run using debug mode (assuming latest master):
`node main.js --debug skype`

and provide the console output here when the error occurs.

**Comment by phillipadsmith** [comment]
Nothing useful, just:
<img width="509" alt="1__node_main_js_--debug_skype__node_" src="https://cloud.githubusercontent.com/assets/34128/14774875/a65b22f2-0a6f-11e6-86be-d9bf5a3c9982.png">

**Comment by mrkno** [comment]
Hmmmmm seems like we haven't updated skype since we changed how we log things. So you said some commands did work? Aside from help, are there any specific ones that fail?

**Comment by phillipadsmith** [comment]
> Hmmmmm seems like we haven't updated skype since we changed how we log things. So you said some commands did work? Aside from help, are there any specific ones that fail?

`!help <query>` works fine for most modules.

A few modules are throwing errors like `!currency 100 CAD in USD` and the `!help currency` also seems to have a problem.

Not sure if that's helpful. Let me know if there's more I can investigate.

**Comment by mrkno** [comment]
In `skype.js` can you add a `console.log(message)` above `skype.sendMessage(thread, message);` (in `sendMessage`.

Can you also put a `console.log(event)` above `callback(platform, event);` in `skype.js`.

**Comment by phillipadsmith** [comment]
Hmmm... nothing much more helpful:

System has started. Hello World!
{ thread_id: '8:phillipadsmith',
  sender_id: 'phillipadsmith',
  sender_name: 'Phillip Smith',
  body: '!help' }
  _  __
 | |/ /__ _ ___ ___ _   _
 | ' // _` / __/ __| | | |
 | . \ (_| \__ \__ \ |_| |
 |_|\_\__,_|___/___/\__, |
                    |___/
 3.1.7
--------------------
https://github.com/mrkno/Kassy

→ !creator
	Lists contributors to this platform
→ !disable
	Disables the platform
→ !help
	displays this help
→ !help <query>
	prints help for a specific module
→ !issue "<title>" <debugLevel>
	posts an issue to github
→ !issue "<title>" "<description>" <debugLevel>
	posts an issue to github with a description
→ debugLevel can be basic, detail or full
	defaults to basic if not specified
→ !kpm
	Kassy Package Manager, for installing external kpm modules
→ !ping
	Checks to see if the platform is alive
→ !restart
	Restarts the platform
→ !shutdown
	Shuts down the platform
→ !update
	Updates the platform to the latest version on master
→ !uptime
	Shows how long the platform has been alive
→ !8ball <query>
	Answers your questions to life.
→ !anim <query>
	Searches for animated GIF.
→ !associate "<hook>" "<text>" or clear
	Associate and disassociate a phrase with another.
→ !currency <number> <from-currency> in <to-currency>
	Converts between currencies.
→ !fawlty
	Fixes fawlty code. Probably.
→ !gif <query>
	Searches for animated GIF.
→ !idea
	Generates an idea for your next StartUp.
→ !insult
	Will almost certainly return profanity.
→ !joke
	A mixed bag of fun.
→ <text>++
	Increases <text>'s karma.
→ <text>--
	Decreases <text>'s karma.
→ !karma
	Shows all current karma.
→ !lithp
	Speaks with a lisp
→ !pickup
	Relationship advice.
→ !pirate <message>
	Translates your message into pirate speak.
→ !profound
	Calculates the meaning of life. You probably wouldn't understand
→ !programmer
	Reactions of a programmer.
→ !quote <person>
	Attempts to get a quote by said person
→ !runbot <jscode>
	Runs JS code.
→ !slap <infidel>
	Slaps an annoying infidel - descriptively!
→ !tictactoe <opponent's full name>
	starts a new game against the specified opponent
→ !move <row><column>
	places a piece at the specified row and column, if you are in a game
→ !surrender
	gives up on a game
→ !vampire
	Makes things sound like a vampire
→ !vote "<question>" <optionalTimeout> "<answer1>" "<answer2>"
	Call a vote on a question.
→ !vote cancel
	cancel the current vote.
→ !vote <number>
	vote for an option.

Something went wrong!Failed to send message.

**Comment by ShyykoSerhiy** [comment]
It seems like it's a bug in skyweb itself. Created issue https://github.com/ShyykoSerhiy/skyweb/issues/27.

**Comment by mrkno** [comment]
I beleive this is fixed as of https://github.com/concierge/Kassy/pull/175/commits/4a048e1387024e1d8ebcad24794db741f7426d4d. Reopen if it isn't.

**Comment by phillipadsmith** [comment]
👍

**Comment by phillipadsmith** [comment]
```Failed to send message..
 Error code: 400.
 Error: null.
 Body: {"errorCode":201,"message":"Failure due to: InvalidParameter."}
```

**Comment by mrkno** [comment]
damn :(. I tried but couldn't replicate it.

**Comment by mrkno** [comment]
Anyone coming here to look for a solution to this problem:  
I suggest using https://github.com/concierge/Concierge/blob/feature/109-Skype-bot-support/core/core_integrations/MSBot.js instead of the skype support currently in master. Even in its undocumented and unfinished state it is more stable than default skype.

**Comment by Awarua-** [comment]
MSBot, is now in master.
