### ISSUE TITLE
Discord support

### ISSUE THREAD

**Issue by lagleki** [concierge/Concierge#165]
example: https://github.com/reactiflux/discord-irc

**Comment by mrkno** [comment]
Longer term we do intend to fully support Discord, for now however (aside from the shutdown, update and restart commands) you can currently use the hubot adapter with no modifications within Kassy:
https://github.com/thetimpanist/hubot-discord

Just clone it into the core/core_integrations directory, create a new section in the main config.json that looks a little like the following:
```json
{
...
    "output": {
        "hubot-discord": {
            "ENV_HUBOT_DISCORD_EMAIL": "<DiscordBotUsername>",
            "ENV_HUBOT_DISCORD_PASSWORD": "<DiscordBotSecret>",
            "ENV_HUBOT_DISCORD_TOKEN": "<DiscordBotToken>",
            "commandPrefix":"!"
        }
    }
...
}
```
The parts between the `<>` can be generated [here](https://discordapp.com/developers/applications/me).

To start use `node main.js hubot-discord`

**Comment by lagleki** [comment]
@mrkno do you mean I should get "package.json" aving the following path "/Kassy/core/core_integrations/hubot-discord/package.json"?

**Comment by mrkno** [comment]
I mean you should follow this: https://github.com/concierge/Kassy/issues/180#issuecomment-230069942
It would give you a working discord output with the exception of shutdown and restart.
