### ISSUE TITLE
What does /restart do in 3.5.1

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Concierge#186]
Previously, when /restart was sent, any code changes in the telegram.js module were picked up. In 3.5.1 this does not appear to be the case anymore?

**Comment by mrkno** [comment]
It will be a require being used somewhere a `require.once` should be.

**Comment by phillipadsmith** [comment]
> It will be a require being used somewhere a require.once should be. Restart as always should reload as much code as possible within the system.

Just to clarify, in 3.5.1+ I should be using `require.once` vs. `require.safe` or `require`?

**Comment by mrkno** [comment]
- If you are requiring anything that you want to be hotswappable but isn't from NPM: `require.once`
- Otherwise `require` or `require.safe` (since a little while ago `require` === `require.safe`)

**Comment by mrkno** [comment]
@phillipadsmith now that #175 is merged, can you verify if this is still a problem?

**Comment by phillipadsmith** [comment]
> @phillipadsmith now that #175 is merged, can you verify if this is still a problem?

Hmmm...

* Pulled `master`
* Put my module folder in `modules`
* Ran `node main.js test telegram`
* Program hangs...

```Loading module 'Module Name'...
Installing "handlebars" from npm.
```
Just sits there. Can't SIGINT or anything. 

If I run it again, it works. So I'm wondering if there was an network problem with NPM and the script just stalls? 

Also, related question, I've got some specific versions of NPM modules needed for the custom module I'm working on -- how can I get Kassy to install those vs. just installing whatever it thinks it needs based on `require` statements?

**Comment by mrkno** [comment]
Not entirely certain what is happening there - we just call the NPM api in the same way the actual NPM executable does. My guess on the hang is something with `deasync` which we are unlikely to ever be able to fix :(

Short answer to second query: there is no current easy way to do this (our whole hotswap/npm system is a hack to begin with, its not a use case I've ever really needed).

For specific versions I suppose someone could always add yet another section to `kassy.json` with a similar format to `package.json` and make sure each dependency is installed and required to the right version number.

**Comment by mrkno** [comment]
@phillipadsmith we are now using a different approach to installing packages from `npm` which may help with this issue - reopen if your problem still exists.
