### ISSUE TITLE
Best approach to log everything, not just matched commands? 

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Concierge#188]
@mrkno For the benefit of evaluating how well the bot is working to meet user's needs, I'm logging the commands and responses to the commands. 

However, I realize that it's actually more useful to log everything, including all of those interactions that don't result in an export.match / result from a module.

Where would be the best place to do this? In a separate `logging.js` module that matched on everything? That was my first thought...

**Comment by phillipadsmith** [comment]
Of course, now that I actually write it out, I realize that this module wouldn't automatically have access to the other matches/responses from other modules... Hmmmmm.

**Comment by mrkno** [comment]
You can just use a `console.debug` inside your integration. That will only ever execute when the `--debug` CLI argument is passed.

**Comment by phillipadsmith** [comment]
I'm not explaining myself well...  :-/ 

I am "logging" in the sense that I want to record any/all interactions with the bot by users, so that I can better understand how they're using the bot. 

Thus, in the specific module, I am logging the username, the command that matched, the response, and so on (for later analysis and reporting). 

However, I also want to record input that did _not_ match any command, e.g., if the user sends "Hello?," I want to log that too.

And, if the user sends a "core" command, like `/help`, I'd also like to be able to log that. 

Best approach toward doing this?

**Comment by mrkno** [comment]
Ok. Well provided @Awarua- approves the #175 PR soon it should be easy to do with a module.

Make a new module, set its priority to last and just log everything that comes your way. The event object will tell you if it has been matched (I can't remember if it will tell you what by or just how many commands matched, but you can always add to the event object in your other modules if you want more data, just do a `event.foo = bar` and it will be passed on). For this to work, *none* of your modules should return anything other than `false` in their `exports.run` method.

Breif example:

kassy.json
```json
{
    "name":"logger",
    "version":1.0,
    "priority":"last",
    "startup":"logger.js"
}
```

logger.js
```javascript
exports.match = () => {
    return true;
};

// I intend to make this optional in future in case it doesn't actually respond to commands
exports.help = () => {
    return [];
};

exports.run = (api, event) => {
    /*
    *  Do the logging here
    *  - event should have some information about previous matches
    *  - if not just add to it (and if you have a good idea for modifications, PR!)
    *  - this module will always run last unless there is another module with priority=last
    */

    // example only, could also dump to a file
    // that being said you can start with --log if you want console in a file
    console.log(JSON.stringify(event, null, 4));
};
```

**Comment by mrkno** [comment]
@phillipadsmith if you need the features from that PR in quickly, as you are a collaberator on the project you are also welcome to perform the code review

**Comment by Awarua-** [comment]
@phillipadsmith @mrkno PR is now merged, sorry for the delay

**Comment by mrkno** [comment]
@Awarua- np

**Comment by mrkno** [comment]
@phillipadsmith Also note: thanks to loopback a logging module will also get responses to the users (that might/might not be what you want)

**Comment by mrkno** [comment]
Any reason to keep this open?

**Comment by phillipadsmith** [comment]
Nope!
