### ISSUE TITLE
event_source incorrectly reports Skype as Facebook

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Concierge#191]
@mrkno No idea where/why this is happening on 4.0alpha:

```
{ thread_id: '8:phillipadsmith',
  sender_id: 'phillipadsmith',
  sender_name: 'Phillip Smith',
  body: '!start',
  event_source: 'facebook',
  arguments: [ '!start' ],
  arguments_body: '',
  module_match_count: 1 }
```

That was sent from Skype. 

This only happens if I'm running several integrations together, e.g., Telegram, Facebook, and Skype. 

Basically, it looks like event.source gets set once on startup in integrations.js and then doesn't get updated on subsequent events.

Is there a quick fix? I've poked at it and can't see anything obviously wrong. :-/

**Comment by phillipadsmith** [comment]
I should say, it's gets the first event's source and then it never updates, e.g., if I first interact with the bot on Telegram, all subsequent events have the event_source set to telegram.

**Comment by mrkno** [comment]
Resolved in https://github.com/concierge/Concierge/pull/193/commits/4a7f118a801e3ff70c4827c865eb7eb96fdc7cb0
