### ISSUE TITLE
Documentation needs to be updated for all the features added in 4.0.0alpha

### ISSUE THREAD

**Issue by ParasDPain** [concierge/Concierge#192]
Just adding this here, to keep track of and other related tasks regarding the newly added features in `4.0.0alpha`. Really looking forward to some of those feature and want to re-write the **Hello World** module to reflect those features.

I'll be happy to work on the documentation myself but can't promise a detailed job as I lack the required familiarity with the new features.

**Comment by mrkno** [comment]
You are welcome to take any of the rewriting or documentation tasks, they are getting a bit behind. If you need repo access for any of the repositories summon me.

**Comment by mrkno** [comment]
@ParasDPain A list of some of the things that have changed:

- Multiple matches of a module are now allowed
- Match counter in `event` object
- Match source in `event` object
- No such thing as a core module anymore
    - `exports.platform` in module
- `api.sendMessageToMultiple`, `platform.getApis`, integration `api.getApi` and integration `api.getUsers`
- SIGINT and SIGHUP will **attempt** a clean shutdown
- KPM table URL can be customised
- Localisation service
- `kassy.json:priority` field (any int, `first`, `last` or `normal`)
- loopback (internal, integrations should still not allow it)

**Comment by ParasDPain** [comment]
Thanks! That will help a lot 😄

**Comment by mrkno** [comment]
Another few:
- `exports.help` is now optional
- `kassy.json:help` strings are now translated by default
- all core modules are uninstallable, and are installed by default on first run

**Comment by ParasDPain** [comment]
Cheers! Progress can be tracked [here](https://github.com/ParasDPain/Kassy/commits/documentation-update)

**Comment by ParasDPain** [comment]
Q1. Are all modules uninstallable by kpm or do you mean they can be removed from the directory without affecting concierge's startup?

Q2. What are benefits of having `exports.platforn` in module?

**Comment by mrkno** [comment]
A1. Core modules including `kpm` itself can now be uninstalled. The `core_modules` directory can have stuff installed into it currently but I don't see any reason long term to keep that functionality. All of the previous `core_modules` are just now normal modules so can be installed/uninstalled as needed.

A2. `exports.platform` allows you to control the overall bot. So for example, the `shutdown` module uses it to shutdown the bot, the `restart` one to restart, `kpm` to load/unload modules.... Basically everything you couldn't do before you can now.

**Comment by ParasDPain** [comment]
**Update**: Due to unexpected workload I'll be busy for the next few months FML

In the meantime, anyone js welcome to pick up the progress and continue or I'll get to it when the time comes

**Comment by mrkno** [comment]
https://github.com/concierge/Concierge/issues/211 is a reminder that we need to finish this. Maybe we could divide and conquer so that it doesn't take any one of us more time than we have to spare.

**Comment by ParasDPain** [comment]
Agreed! How do you suggest we divide the task? I'll try to manage some time

**Comment by mrkno** [comment]
3 tasks, I'll see if I can get @Awarua- involved so we get one each. I suppose given I wrote ~90% of the API I can do the documentation of that.

**Comment by ParasDPain** [comment]
Great! I can start with the Intro topics and perhaps write some tutorials/demonstrations

**Comment by mrkno** [comment]
A thought for making initial config easier: maybe kpm should have an optional web-based GUI. In a similar way that luci is to opkg/openwrt.

I won't be doing that anytime soon though

**Comment by ParasDPain** [comment]
Sounds good, though while we're at it, might as well develop a full fledged GUI and installer as discussed in #180

**Comment by mrkno** [comment]
#212 had the API documentation updates

**Comment by ParasDPain** [comment]
Great! I should have some time this Saturday to work on the rest.

**Comment by ParasDPain** [comment]
So I was looking at the TODO and you've done most of it in the PR 😆 So I'll be writing a few tutorials on using different features provided by `api`,  `event` and perhaps `exports.platform` then.

Additionally, what are your thoughts on integrating a CLI changelog like ohmyzsh for users who've updated after a while? It'll just be more documentation to maintain after an update though :/

**Comment by mrkno** [comment]
I like the idea of a changelog, but don't really want to maintain it. Provided commit messages are kept sensible it may be possible to generate one.

As for what remains to do, the main README probably needs an update. I also only focussed on API changes rather than actually updating the docs, so there still may be some things that need changing. In particular I think the post-install (initial setup) probably needs to be made easier.

**Comment by ParasDPain** [comment]
A simple commit-message is upto the writer's opinion but sounds like the best solution.

Sweet, I'll have a look at the README and post-install

**Comment by mrkno** [comment]
@ParasDPain do you have any more changes to make on this, or do you consider your changes to be 'complete'?

**Comment by ParasDPain** [comment]
The documentation is updated enough to help with using v4.0 features which was my aim. Additionally, a few docs can be updated to follow the overall documentation stylistically but is not an urgent need. We can also write a few tutorials to suggest stylistic approaches on using core features but is not an urgent need as well. 

I'd be happy to make more changes for anything you might've found in need of updating.

**Comment by mrkno** [comment]
I suggest closing this issue as #217 will require documentation and any further changes can be made in there. 

Some tutorials would be good but there is no rush. I think the hello world that we have is probably sufficient for the absolute basics.

**Comment by ParasDPain** [comment]
Sounds good!
