### ISSUE TITLE
Make Integrations and Services installable modules

### ISSUE THREAD

**Issue by mrkno** [concierge/Concierge#217]
- Allow integrations to be installed, uninstalled and configured at runtime
- Allow modules to be 'services' (that is, no I/O, only start/stop)
- Add onload/unload module events - all ES6 code should extend EventEmitter so we get events by default.  Useful for services.
- Allow I/O interception (middleware). Also useful for services.

Reasoning:
- Feature parity and requests
- Makes Concierge [even more] modular
- Reduces complexity of Concierge core
- Events reduce dependence on implementation, only on emitted data.
- Allows modules such as [boss](http://github.com/concierge/boss) to manage the Concierge platform without modifying it.

**Comment by mrkno** [comment]
@Awarua- are you willing to take on any of this (or finish MSBots) amoungst the tonne of other things we need to get done?

**Comment by Awarua-** [comment]
I'll finish MSBots, but I can help with this, once uni work is not so much of a pressure
