### ISSUE TITLE
Weird error breaks facebook integration via the currency module

### ISSUE THREAD

**Issue by ParasDPain** [concierge/Concierge#222]
Build version: **4.0.0-alpha.4.2**
Impact: **Critical error log. Concierge continues running unaffected**

Steps to Reproduce:
- Install the [currency](https://github.com/concierge/currency) module via kpm
- Send any query to the module with the currencies capitalized. For e,g. `/currency 20 NZD in USD`

Error Log:

> CRITICAL ERROR WAS UNHANDLED:
> Error: A thread ID must be specified.
>   at _class.sendMessage (/root/Dev/concierge/core/core_integrations/facebook.js:77:27)
>   at /root/Dev/concierge/modules/kpm_currency/currency.js:30:13
>   at Request._callback (/root/Dev/concierge/modules/kpm_currency/currency.js:59:13)
>   at Request.self.callback (/root/Dev/concierge/node_modules/request/request.js:187:22)
>   at emitTwo (events.js:100:13)
>   at Request.emit (events.js:185:7)
>   at Request.<anonymous> (/root/Dev/concierge/node_modules/request/request.js:1048:10)
>   at emitOne (events.js:90:13)
>   at Request.emit (events.js:182:7)
>   at IncomingMessage.<anonymous> (/root/Dev/concierge/node_modules/request/request.js:969:12)
>   at emitNone (events.js:85:20)
>   at IncomingMessage.emit (events.js:179:7)
>   at endReadableNT (_stream_readable.js:913:12)
>   at _combinedTickCallback (internal/process/next_tick.js:74:11)
>   at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by ParasDPain** [comment]
😪 Alright I Fixed it in this [commit](https://github.com/concierge/currency/commit/8bc52a3ea44de2ab00a9ced5b294adb4ff67c160)

**Comment by mrkno** [comment]
I had wondered why currency was broken, now I know
