### ISSUE TITLE
Question: Different ways of running an automated module

### ISSUE THREAD

**Issue by ParasDPain** [concierge/Concierge#225]
The aim is to access the `api` object for sending a message anytime a message is sent in a thread. `exports.match` is always called for matches so my **hack** was to set a local variable with the state from `exports.match` and return `true` to access said variable in `exports.run`; check the state and send the appropriate message using `api`.

```javascript
var state = false;
exports.match = (event, commandPrefix) => {
    state = true;
    return true;
}

exports.run = (api, event) => {
    if(state) {
        api.sendMessage(automatedFoo(), event.thread_id);
    }
}
```

Is there an easier/alternative way of doing this? I'm probably forgetting something fundamental provided by the API.

**Comment by mrkno** [comment]
Hmmm. So to clarify you are just trying to use the `api` whenever a message is received from a particular integration? I probably need more detail on the specific task to give helpful suggestions.

Modifying your current example to be slightly less of a hack and avoid race conditions:
```js
exports.match = (event) => {
    event.state = true; // event object will be preserved between match and run
    return true;
}

exports.run = (api, event) => {
    if(event.state) {
        api.sendMessage(automatedFoo(), event.thread_id);
    }
}
```

You could just match everything and perform your matching task inside run.
```js
exports.match = () => true;
exports.run = (api, event) => {
    if (event.event_source === 'wherever') {
        // do your thing
    }
}
```
although I don't see currently why this check can't be done as follows:
```js
exports.match = (event) => event.event_source === 'whatever';
exports.run = (api, event) => {
    // do thing
}
```

In general `match` should only be used to determine if your module should run, not how it should run or what to do when it is running - there are always exceptions to this (`associate` passes information from its match method to its `run` method to avoid a duplicated search).

**Comment by ParasDPain** [comment]
Thank you for the pointers! I'm currently writing a module that basically checks the current date once Concierge has started (or once user interaction is received from an integration) and sends a message if it's the special day. It's like a birthday-wishing module.

Ideally, I'd like to perform the logic without interaction from a user; once integrations have successfully loaded.

**Comment by mrkno** [comment]
> once integrations have successfully loaded

That is a difficult one... some integrations like facebook report that they are loaded when they actually aren't (nothing we can do to fix that I am aware of). There is a current hacky approach to finding out if they are loaded in the `say-hi` module, but that only works a portion of the time. In the beta branch this problem still exists but can be handled a little more gracefully by listening for the `start` event.

Have you considered a different approach? Perhaps when the module is loaded, it could check on an interval timer if the date is a particular one (or even make a timeout that will callback at exactly the right time for the next event). Then you could use `exports.platform.getIntegrationApis()` to get the appropriate api and send the message. 

This would mean you aren't waiting for someone to send a message to your module and it would work independently of the status of the integrations (if an integration isn't running when the callback occurs, just don't send the message).

**Comment by ParasDPain** [comment]
Great idea! Thanks I'll try that; might have to store `thread_id` some way. I'll update here as things progress.

Thanks for the link

**Comment by mrkno** [comment]
Does this issue still need to be open?

**Comment by ParasDPain** [comment]
I believe not. The project has gone stale and I'll re-open if I REALLY need to.

Thanks
