### ISSUE TITLE
Unhandled Error crashes Concierge's process

### ISSUE THREAD

**Issue by ParasDPain** [concierge/Concierge#228]
**Tested On**
Concierge 4.0 beta.0 running on Kali 2.0 Linux

**Steps to reproduce**
- Start Concierge with an integration (utilizing the internet). I used `node main.js --debug --log facebook`
- Turn off the internet
- The integration will crash, taking Concierge down with it

**What happened**
Concierge's node process crashes returning nothing to shell

**Expected behavior**
The integration crashes and Concierge returns with error code `255` as it exits.

**Debug Log**
```
ERR! ERROR in listen -->  Error: getaddrinfo ENOTFOUND 0-edge-chat.facebook.com 0-edge-chat.facebook.com:443 
ERR! ERROR in listen -->    at errnoException (dns.js:26:10)
ERR! ERROR in listen -->    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
ERR! ERROR in listen -->  
ERR! ERROR in listen -->   { [Error: getaddrinfo ENOTFOUND 0-edge-chat.facebook.com 0-edge-chat.facebook.com:443 ]
ERR! ERROR in listen -->    cause: 
ERR! ERROR in listen -->     { [Error: getaddrinfo ENOTFOUND 0-edge-chat.facebook.com 0-edge-chat.facebook.com:443 ]
ERR! ERROR in listen -->       code: 'ENOTFOUND',
ERR! ERROR in listen -->       errno: 'ENOTFOUND',
ERR! ERROR in listen -->       syscall: 'getaddrinfo',
ERR! ERROR in listen -->       hostname: '0-edge-chat.facebook.com',
ERR! ERROR in listen -->       host: '0-edge-chat.facebook.com',
ERR! ERROR in listen -->       port: 443,
ERR! ERROR in listen -->       rawStackTrace: [ CallSite {}, CallSite {} ] },
ERR! ERROR in listen -->    isOperational: true,
ERR! ERROR in listen -->    code: 'ENOTFOUND',
ERR! ERROR in listen -->    errno: 'ENOTFOUND',
ERR! ERROR in listen -->    syscall: 'getaddrinfo',
ERR! ERROR in listen -->    hostname: '0-edge-chat.facebook.com',
ERR! ERROR in listen -->    host: '0-edge-chat.facebook.com',
ERR! ERROR in listen -->    port: 443,
ERR! ERROR in listen -->    rawStackTrace: [ CallSite {}, CallSite {} ] }
Unhandled rejection Error: Error: getaddrinfo ENOTFOUND 0-edge-chat.facebook.com 0-edge-chat.facebook.com:443 
  at /root/Dev/concierge/modules/kpm_facebook/facebook.js:127:23
  at /root/Dev/concierge/node_modules/facebook-chat-api/src/listen.js:218:9
  at tryCatcher (/root/Dev/concierge/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._settlePromiseFromHandler (/root/Dev/concierge/node_modules/bluebird/js/main/promise.js:510:31)
  at Promise._settlePromiseAt (/root/Dev/concierge/node_modules/bluebird/js/main/promise.js:584:18)
  at Promise._settlePromises (/root/Dev/concierge/node_modules/bluebird/js/main/promise.js:700:14)
  at Async._drainQueue (/root/Dev/concierge/node_modules/bluebird/js/main/async.js:123:16)
  at Async._drainQueues (/root/Dev/concierge/node_modules/bluebird/js/main/async.js:133:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/root/Dev/concierge/node_modules/bluebird/js/main/async.js:15:14)
  at tryOnImmediate (timers.js:534:15)
  at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by mrkno** [comment]
Hmmm thats a new one, I haven't seen it before. For some reason the uncaughtException handler at platform.js:28-47 didn't catch your exception. As for why Concierge crashed, I suspect that is because when facebook died it took the event queue with it, terminating the program. Starting with multiple integrations would work around that problem if it is the cause.

**Comment by ParasDPain** [comment]
Thank you for the quick patch 👍
I pulled the new changes and the exception is being caught now but Concierge continues exiting without returning an error code. 
Alternatively, I ran Concierge with more than one integrations (`facebook` and `test`) and that did avoid the crash but it's only a workaround

**Debug Log**
```
ERR! ERROR in listen -->  Error: getaddrinfo ENOTFOUND 0-edge-chat.facebook.com 0-edge-chat.facebook.com:443 
ERR! ERROR in listen -->    at errnoException (dns.js:26:10)
ERR! ERROR in listen -->    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
ERR! ERROR in listen -->  
ERR! ERROR in listen -->   { [Error: getaddrinfo ENOTFOUND 0-edge-chat.facebook.com 0-edge-chat.facebook.com:443 ]
ERR! ERROR in listen -->    cause: 
ERR! ERROR in listen -->     { [Error: getaddrinfo ENOTFOUND 0-edge-chat.facebook.com 0-edge-chat.facebook.com:443 ]
ERR! ERROR in listen -->       code: 'ENOTFOUND',
ERR! ERROR in listen -->       errno: 'ENOTFOUND',
ERR! ERROR in listen -->       syscall: 'getaddrinfo',
ERR! ERROR in listen -->       hostname: '0-edge-chat.facebook.com',
ERR! ERROR in listen -->       host: '0-edge-chat.facebook.com',
ERR! ERROR in listen -->       port: 443,
ERR! ERROR in listen -->       rawStackTrace: [ CallSite {}, CallSite {} ] },
ERR! ERROR in listen -->    isOperational: true,
ERR! ERROR in listen -->    code: 'ENOTFOUND',
ERR! ERROR in listen -->    errno: 'ENOTFOUND',
ERR! ERROR in listen -->    syscall: 'getaddrinfo',
ERR! ERROR in listen -->    hostname: '0-edge-chat.facebook.com',
ERR! ERROR in listen -->    host: '0-edge-chat.facebook.com',
ERR! ERROR in listen -->    port: 443,
ERR! ERROR in listen -->    rawStackTrace: [ CallSite {}, CallSite {} ] }
"kpm_facebook" threw up. <unknown> is now covered in sick.
Error: Error: getaddrinfo ENOTFOUND 0-edge-chat.facebook.com 0-edge-chat.facebook.com:443 
  at /root/Dev/concierge/modules/kpm_facebook/facebook.js:127:23
  at /root/Dev/concierge/node_modules/facebook-chat-api/src/listen.js:218:9
  at tryCatcher (/root/Dev/concierge/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._settlePromiseFromHandler (/root/Dev/concierge/node_modules/bluebird/js/main/promise.js:510:31)
  at Promise._settlePromiseAt (/root/Dev/concierge/node_modules/bluebird/js/main/promise.js:584:18)
  at Promise._settlePromises (/root/Dev/concierge/node_modules/bluebird/js/main/promise.js:700:14)
  at Async._drainQueue (/root/Dev/concierge/node_modules/bluebird/js/main/async.js:123:16)
  at Async._drainQueues (/root/Dev/concierge/node_modules/bluebird/js/main/async.js:133:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/root/Dev/concierge/node_modules/bluebird/js/main/async.js:15:14)
  at tryOnImmediate (timers.js:534:15)
  at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by mrkno** [comment]
Being caught now it will at least not bring down other integrations with it. As for the other problem, it is simply because there is no while(true) loops keeping Concierge alive, however a crash is probably appropriate cause there is nothing other than a ctrl + c you could do to interact with it anyway. We don't know if it is safe to save the config or unload modules cause who knows what the integration did to the platform as a whole. Thoughts?

**Comment by ParasDPain** [comment]
Agreed, a crash is appropriate but I was using a simple `sh` to continuously restart Concierge if it didn't return `0`. 
```sh
#!/bin/sh

cd Path/To/Concierge/Directory
until node main.js --debug --log test facebook; do
  echo "Concierge crashed on $(date), restarting now..." >&2;
  sleep 1;
done
```
The crash broke it as no error was returned. I guess it's about time I moved to `forever.js` or fixed the `heroku` build

**Comment by mrkno** [comment]
There is an auto_restart module for the facebook problem FYI...

**Comment by ParasDPain** [comment]
Part of the problem on my local build is the broken wifi driver which drops off the connection randomly. I could look into how `auto-restart` handles that since restarting `facebook` won't always solve the problem

**Comment by ParasDPain** [comment]
@mrkno Is there scope for returning an error code when this case happens; or should we call this resolved and close the issue?

**Comment by mrkno** [comment]
The problem is more of 'how' than is there scope to. Concierge crashes because there is no longer an event loop running to keep it alive - there is no current place in the code you could easily determine what the error code should be. Error handling between integrations and general modules is performed the same way...

It would be possible to listen for the error event in a custom service and check if it was an integration (similar to `auto-restart`), then set process.exitCode which would be returned from Concierge moments later when the event loop died.

**Comment by ParasDPain** [comment]
I see, so we can temporarily patch it using a service. The service may also be needed in the default installation path.

I'll give it a go.

**Comment by ParasDPain** [comment]
[`crash-handler`](https://github.com/concierge/crash-handler) patches the issue.
