### ISSUE TITLE
exports.config property not persisted from exports.stop

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Concierge#230]
Howdy,

I'm seeing an issue on 4.0.0-beta.1 where any export.config property I try to set in the exports.stop method is not persisted to the config.json as it was in the past.

Feature or bug?

Phillip.

**Comment by mrkno** [comment]
Combination. The behaviour is as designed (nothing is explicitly broken) but the use case is no longer supported (when it should be). Config is now a module in its own right, so unfortunately is being unloaded before your one is. If I ever get time (or anyone else ever does) I was going to introduce a new module type (`system`) which is always loaded before and unloaded after any other such that this could be avoided.

**Comment by mrkno** [comment]
As a workaround, you could experiment with the `priority` and `name` fields of `kassy.json` to force it to be ordered before the config module.

**Comment by phillipadsmith** [comment]
@mrkno Hmmm... this isn't what I'm seeing. If I move the ```exports.config.offset = offset;``` line out of the `stop` method it still doesn't get persisted to the configuration file when Concierge shuts down.

**Comment by phillipadsmith** [comment]
@mrkno Scratch that. It does appear to be working now when I persist to config outside of the stop method.

**Comment by phillipadsmith** [comment]
@mrkno I've worked around this is a non-optimal way for the Telegram module, [as shown here](https://github.com/concierge/telegram/commit/5ea6902f0dbdc5aae39d948be7e6c492ea94a2a4).

**Comment by mrkno** [comment]
It would be better to just fix the problem permanently, if only I had time...

**Comment by phillipadsmith** [comment]
> It would be better to just fix the problem permanently, if only I had time...

How can I / we help? (Not that I have an abundance of it either, obviously!)

**Comment by mrkno** [comment]
A new concierge module type needs to be added ('system') and the module loader needs to read all hubot/kassy.json files AOT. Once both of those are done it will be relatively simple to fix.

**Comment by mrkno** [comment]
Note you will now need to install the `config` module from `KPM`
