### ISSUE TITLE
Commands "falling through" to other modules / multiple matches on command?

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Concierge#231]
I was troubleshooting an issue with the "logging module" approach that was discussed in issue https://github.com/concierge/Concierge/issues/188 that appeared when I switched to 4.0.0-beta.1

The issue appears to be that commands now "fall through" to other modules, or -- put another way -- it's possible to have multiple matches on the same command.

This seems like a major departure from how things work before, which I believe was that once a command matched that no further processing by other modules would happen?

Forgot to add the question: Is this a feature, or a bug?

**Comment by mrkno** [comment]
Feature, it has been there for a few of the alpha versions due to an earlier feature request.
Add `return true;` at the end of your run method or set `event.shouldAbort = true;` within your module.

Logging may now be easier using middleware FYI (it was one of the reasons I added it, cause I wanted a less hacky solution).

**Comment by phillipadsmith** [comment]
> Logging may now be easier using middleware FYI (it was one of the reasons I added it, cause I wanted a less hacky solution).

Is there documentation on middleware?

> Feature, it has been there for a few of the alpha versions due to an earlier feature request.
Add return true; at the end of your run method or set event.shouldAbort = true; within your module.

Okay, I'll give that a try.

**Comment by mrkno** [comment]
> Is there documentation on middleware?

WIP, I would have more if I had more time, it follows a similar format to most other node applications though.

Rough example (may have to check the arguments passed to the callback func for exact details):
```js
// subscribe
exports.platform.use('<hook>', callbackFunc);
// unsubscribe
exports.platform.unuse('<hook>', callbackFunc);

const callbackFunc = (next, args...) => {
    // do stuff
    next();
};
```

can modify arguments:
```js
const callbackFunc = (next, arg1,arg2) => {
    arg1 = 'foo';
    const newArg = 'baz';
    next(arg1, arg2, baz);
};
```

**Comment by phillipadsmith** [comment]
> Rough example (may have to check the arguments passed to the callback func for exact details):

Helpful.

Is there any middleware that's been developed yet to use as a reference?

**Comment by mrkno** [comment]
Considering that it has only just been made, no. Disable and admin may be ported to it if time permits.
