### ISSUE TITLE
Loading new integration: Best practices?

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Concierge#232]
So, when loading the Telegram integration for the first time, I'm seeing an error as follows:

```
System has started. Hello World!
Concierge-bot> /kpm install https://github.com/concierge/telegram.git
Attempting to install module from "https://github.com/concierge/telegram.git"...
Loading module 'telegram'... 	Installing "tgfancy" from npm.
Installation complete.
Installing "configstore" from npm.
Installation complete.
[DONE]
"telegram" (4) is now installed.
"!CORE!" threw up. <unknown> is now covered in sick.
```

... so I'm wondering, what is the best way to approach this need for the configuration (token, etc.) before the module is loaded and started?

**Comment by mrkno** [comment]
You can use kpm config before loading any module. Additionally, the current integrations are only reading their config after start is called (requires kpm start). In load, the configuration might be initialised (defaults set) but not read.

**Comment by phillipadsmith** [comment]
> Additionally, the current integrations are only reading their config after start is called (requires kpm start). In load, the configuration might be initialised (defaults set) but not read.

Ah, yes, that makes sense. I'll fix that up.

**Comment by mrkno** [comment]
Do you feel it would help to have this mentioned in the docs?
