### ISSUE TITLE
Make boss a default module

### ISSUE THREAD

**Issue by mrkno** [concierge/Concierge#238]
- update defaults
- add documentation
- set version to 4.0 (no beta/alpha)

**Comment by phillipadsmith** [comment]
What is "boss"? :)

**Comment by p0358** [comment]
@phillipadsmith "GUI based Concierge module management (boss is to Concierge what luci is to OpenWRT)"

**Comment by mrkno** [comment]
Basically it is a way to make interacting with and setting up the entire system easier, plus gives some debugging tools.

You can test out the current (mostly working) version by `/kpm install boss`, then go to port `8080` and login as `admin:admin`. Note to install it you need at least NPM version `3.10.0` - not sure why, but the older NPMs seem to fail to install all of its dependencies properly.
