### ISSUE TITLE
Setting version to 0 in kassy.json stops modules from loading

### ISSUE THREAD

**Issue by fallaciousreasoning** [concierge/Concierge#245]
Presumably there's a !module.version check somewhere which is breaking because JavaScript? Not sure how important this is / whether it even counts as a real bug

**Comment by mrkno** [comment]
I don't think we ever considered that version numbers would go below 0.0.1. A very trivial bug to fix if I had a booting computer.

**Comment by fallaciousreasoning** [comment]
See https://github.com/concierge/Concierge/pull/246
